#!/python-venv/bin/python
"""
Listens for all packets from IMPISH and sorts them, sending
them to their respective process for handling.
"""

import os
import socket

from ctypes import sizeof
from impisc import logging
from impisc.packets import HealthPacket, QuicklookPacket, CommandResponsePacket, PacketHeader

# TODO: update this to use definitions within impisc once settled:
HEADER_SIZE = sizeof(PacketHeader)
PACKET_MAP = {
    HEADER_SIZE + sizeof(HealthPacket): int(os.environ["LOCAL_HEALTH_FWD_PORT"]),
    HEADER_SIZE + sizeof(QuicklookPacket): int(os.environ["LOCAL_QUICKLOOK_FWD_PORT"]),
    HEADER_SIZE + sizeof(CommandResponsePacket): int(os.environ["LOCAL_COMMAND_FWD_PORT"]),
}
SORT_PORT = int(os.environ["SORT_PORT"])
LISTEN_ADDR = ("", SORT_PORT)  # The address the relay is sending to, TODO: update this to use environ


def main():
    # Program can only end if killed, and sockets will be released by OS
    # Don't bother closing them
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(LISTEN_ADDR)
    while True:
        data, addr = sock.recvfrom(8192)
        if len(data) > 0:  # For some reason we sometimes get empty packets?
            port = PACKET_MAP[len(data)]
            logging.log_debug(f"Received {len(data)} bytes from {addr[0]}:{addr[1]}")
            logging.log_debug(f"Sending {len(data)} bytes to local port {port}")
            sock.sendto(data, ("", port))
        else:
            logging.log_warning(f"Received zero length packet on {LISTEN_ADDR[0]}:{LISTEN_ADDR[1]}")


if __name__ == "__main__":
    main()
