#!/bin/bash

# Enable systemd-networkd instead of NetworkManager
sudo systemctl disable NetworkManager
sudo systemctl enable systemd-networkd
sudo systemctl start systemd-networkd

# Use the "predictable" net names instead of eth0, eth1, etc.
# Requires a reboot
sudo raspi-config nonint do_net_names 0

fn="01-impish.yaml"
sudo cp $fn /etc/netplan/
cd /etc/netplan
sudo chmod 600 $fn
sudo netplan generate
sudo netplan apply

# For some reason, modifying this by hand helps solve connection issues.
sudo rm /etc/resolv.conf
echo 'nameserver 1.1.1.1' | sudo tee -a /etc/resolv.conf
echo 'nameserver 8.8.8.8' | sudo tee -a /etc/resolv.conf
