#!/bin/bash

# Enable systemd-networkd instead of NetworkManager
sudo systemctl disable NetworkManager
sudo systemctl enable systemd-networkd
sudo systemctl start systemd-networkd

# Allow tunnel for SSH VPN
sudo sed -i 's/#PermitTunnel no/PermitTunnel yes/g' /etc/ssh/sshd_config
sudo systemctl restart ssh sshd

# Use the "predictable" net names instead of eth0, eth1, etc.
# Requires a reboot
sudo raspi-config nonint do_net_names 0

fn="01-impish.yaml"
sudo cp $fn /etc/netplan/
cd /etc/netplan
sudo chmod 600 $fn
sudo netplan apply
