#!/bin/bash

sudo apt -y remove fake-hwclock
sudo update-rc.d -f fake-hwclock remove


# Configure driver bind/unbind permissions
sudo cp 99-i2c-permissions.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules  # Unsure if this is needed if we reboot
sudo usermod -a -G i2c impish

# Comment out block in /lib/udev/hwclock-set
sudo sed -i '/if \[ -e \/run\/systemd\/system \] ; then/,/fi/ { /^#/ !s/^/# / }' /lib/udev/hwclock-set
