#!/bin/bash

# Tell the Pi to mount the additional SD card in /data on boot.
# Checks if the entry already exists in /etc/fstab first

drive="/dev/mmcblk1"
partition="/dev/mmcblk1p1"

partuuid=$(sudo blkid -s PARTUUID -o value $partition)
if [[ -z "$partuuid" ]]; then
    echo "$partition doesn't exist; creating"
    # There is no partition set up on $drive yet:
    # create a GPT table and an ext4 partition
    sudo parted -a optimal $drive --script -- mklabel gpt mkpart primary 0% 100%
else
    echo "$partuuid exists"
fi

# Re-fetch
partuuid=$(sudo blkid -s PARTUUID -o value $partition)
already_set_up=$(cat /etc/fstab | grep "$partuuid")

if [[ -z "$already_set_up" ]]; then
    echo "SD1 not set up yet"
else
    echo "SD1 already set up"
    exit 0
fi

# Format the drive
sudo mkfs.ext4 "$partition"

# Anyone can read/write to the data partition
sudo mkdir -p /data
sudo chmod -R 0777 /data

# See https://man7.org/linux/man-pages/man5/fstab.5.html for info on fstab entry
# See https://man7.org/linux/man-pages/man8/mount.8.html for info on mount options
# in column 4
echome="PARTUUID=\"$partuuid\"   /data   ext4    defaults,noatime,auto,rw 0 2"
echo $echome | sudo tee -a /etc/fstab > /dev/null

sudo mount /dev/mmcblk1p1 /data
