#!/bin/bash

# Enable systemd-networkd instead of NetworkManager
sudo systemctl disable NetworkManager
sudo systemctl enable systemd-networkd
sudo systemctl start systemd-networkd

fn="01-impish.yaml"
sudo cp $fn /etc/netplan/
cd /etc/netplan
sudo chmod 600 $fn
sudo netplan apply
