#!/bin/bash

sudo cp enp1s0-link-down /etc/networkd-dispatcher/no-carrier.d/
sudo cp tun0-trigger /etc/networkd-dispatcher/off.d/
sudo systemctl daemon-reload
sudo systemctl restart networkd-dispatcher
