#!/bin/bash
# Install systemd services and associated process programs

# Install all processes
processes=$(ls ../processes)
for s in $processes; do
    sudo cp --preserve=mode "../processes/$s" "/usr/local/bin"
done

# Install all .service files and enable them
services=$(cat service_names.txt)
for s in $services; do
    sudo cp --preserve=mode "../services/$s" "/etc/systemd/system"
done
sudo cp '../services/variables.env' '/usr/local/bin'
sudo cp '../services/variables.env' '/etc/systemd/system'

sudo systemctl daemon-reload
for s in $services; do
    sudo systemctl restart "$s"
done
