#!/bin/bash

# Stop any running services: need to replace binaries
for serv in $(cat services_to_enable.txt); do
    sudo systemctl stop $serv
done

cd ../rust
cargo build --release
execs=$(find ./target/release -maxdepth 1 -perm -111 -type f)

sudo cp --preserve=mode $execs /usr/local/bin
