#!/bin/bash
sudo apt update
sudo apt install -y networkd-dispatcher stress-ng libgpiod-dev cmake build-essential

if [[ -e "$HOME/.rustup" ]]; then
    rustup update
else
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
