#!/bin/bash

# Stop any running services: need to replace binaries
for serv in $(cat services_to_enable.txt); do
    sudo systemctl stop $serv
done

rustup update
cd ../rust
cargo build --release
execs=$(find ./target/release -maxdepth 1 -perm -111 -type f)

sudo cp --preserve=mode $execs /usr/local/bin

# Restart the services we stopped
sudo systemctl daemon-reload
for serv in $(cat services_to_enable.txt); do
    sudo systemctl restart $serv
done

# Init and install the starspec layer
git submodule update --init --recursive
cd starspec-layer
git checkout main
git pull
cargo build --release
./install-forwarder
