#!/bin/bash

scripts="configure_sd1 setup_directories configure_configtxt configure_network remove_bloat install_scripts configure_system_python_env install_services"
for s in $scripts; do
    echo "executing $s"
    ./"$s"
    echo "done $s"
done

read -p "Reboot now? (leave blank for yes, type something for no) " conf

if [[ -z $conf ]]; then
    sudo reboot
fi
