#!/bin/bash

sudo mkdir -p /data/health
sudo mkdir -p /data/journal
sudo mkdir -p /data/quicklook
sudo mkdir -p /data/science

# Make them editable by anyone
sudo chmod 0777 /data
sudo chmod 0777 /data/health
sudo chmod 0777 /data/journal
sudo chmod 0777 /data/quicklook
sudo chmod 0777 /data/science
