#!/bin/bash

direcs="config debug health science quicklook"
for d in $direcs; do
    sudo mkdir -p /data/$d
    sudo chmod 777 /data/$d
done

# Needed for proper permissions
sudo chown -R root /data/journal
