#!/bin/bash

# Set the timesyncd NTP configuration using the StarSpec gondola NTP address

# NB: update this when we have more info
starspec_ntp_server="0.debian.pool.ntp.org"

cfg=$(cat <<EOF
[Time]
NTP=$starspec_ntp_server
#FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
#RootDistanceMaxSec=5
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048
#ConnectionRetrySec=30
#SaveIntervalSec=60
EOF
)

echo "$cfg" | sudo tee '/etc/systemd/timesyncd.conf'
sudo systemctl restart systemd-timesyncd
