#!/bin/bash
# Execute tun1-trigger when network access is established.

IFACE=$1
ACTION=$2
if [ "$IFACE" = "wlp0s20f3" ] && [ "$ACTION" = "up" ]; then
    etc/NetworkManager/dispatcher.d/tun1-trigger tun1 down
fi
