#!/bin/bash

sudo apt install networkd-dispatcher
sudo systemctl enable --now networkd-dispatcher.service
sudo cp tun1-trigger /etc/NetworkManager/dispatcher.d/
sudo cp 99-on-boot-hook /etc/NetworkManager/dispatcher.d/
sudo sed -i 's/#PermitTunnel no/PermitTunnel yes/g' /etc/ssh/sshd_config
sudo systemctl daemon-reload
sudo systemctl restart ssh sshd networkd-dispatcher
