#!/bin/bash

sudo apt install networkd-dispatcher
sudo systemctl enable --now networkd-dispatcher.service
sudo mkdir -p /etc/networkd-dispatcher/off.d
sudo cp tun0-trigger.sh /etc/networkd-dispatcher/off.d
/etc/networkd-dispatcher/off.d/tun0-trigger.sh
sudo sed -i 's/#PermitTunnel no/PermitTunnel yes/g' /etc/ssh/sshd_config
sudo systemctl restart ssh sshd
