#!/bin/bash

# Configure a virtual environment
# for running programs on the system.

sudo apt install -y python3-venv

pushd /
sudo rm -rf python-venv
sudo mkdir python-venv
sudo chmod -R 777 python-venv
python3 -m venv python-venv
source python-venv/bin/activate

pip install --upgrade pip

popd
pip install ..
cd ..
pip install ..
