#!/bin/bash
# Install systemd services and associated process programs

# Install all processes
processes=$(ls ../processes)
for s in $processes; do
    sudo cp "../processes/$s" "/usr/local/bin"
done

# Install all .service files and enable them
services=$(find ../services/ -maxdepth 1 -type f -name "*.service" -printf "%f  ")
for s in $services; do
    echo $s
    sudo cp "../services/$s" "/etc/systemd/system"
done
sudo cp "../services/gs-variables.env" "/usr/local/bin"
sudo cp "../../services/variables.env" "/usr/local/bin"

sudo systemctl daemon-reload
for s in $services; do
    sudo systemctl enable "$s"
    sudo systemctl restart "$s"
done

# Install all .timer files and enable them
timers=$(find ../services/ -maxdepth 1 -type f -name "*.timer" -printf "%f  ")
for t in $timers; do
    echo $t
    sudo cp "../services/$t" "/etc/systemd/system"
done

sudo systemctl daemon-reload
for t in $timers; do
    sudo systemctl enable "$t"
    sudo systemctl restart "$t"
done
