#!/bin/bash

sudo apt-get update -y
sudo apt-get upgrade -y


# Grafana base
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
sudo apt install -y apt-transport-https wget
sudo mkdir -p /etc/apt/keyrings
sudo wget -O /etc/apt/keyrings/grafana.asc https://apt.grafana.com/gpg-full.key
sudo chmod 644 /etc/apt/keyrings/grafana.asc

echo "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

sudo apt update
sudo apt modernize-sources -y
sudo apt install grafana

sudo systemctl daemon-reload
sudo systemctl enable --now grafana-server

# install gcx (cli control)
sudo apt install -y curl
curl -fsSL https://raw.githubusercontent.com/grafana/gcx/main/scripts/install.sh | sh

echo 'export PATH="/home/impish/.local/bin:$PATH"' >> ~/.bashrc
. ~/.bashrc
