#!/bin/bash
# Install and configure the MySQL server and database

source /usr/local/bin/grafana.env
sudo apt install mariadb-server
sudo systemctl start mysql
sudo mysql -e "CREATE USER 'impish'@'localhost' IDENTIFIED BY '$PASS';" > /dev/null 2>&1  # Suppress printing password ;P
sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'impish'@'localhost';" > /dev/null 2>&1

source /python-venv/bin/activate
python -m impish_monitor.initialize_database
