#!/bin/bash
# Install and configure the MySQL server and database

if [ ! -f /usr/local/bin/grafana.env ]; then
    echo "/usr/local/bin/grafana.env not found! Exitting from install_mysql; add the file then rerun this script and those following."
    exit 1
fi

source /usr/local/bin/grafana.env
sudo apt install mariadb-server
sudo systemctl start mysql
sudo mysql -e "CREATE USER 'impish'@'localhost' IDENTIFIED BY '$PASS';" > /dev/null 2>&1  # Suppress printing password ;P
sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'impish'@'localhost';" > /dev/null 2>&1

initialize_database
