#!/bin/bash

sudo apt-get update -y
sudo apt-get upgrade -y

# Grafana base
# https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
sudo apt install -y apt-transport-https wget
sudo mkdir -p /etc/apt/keyrings
sudo wget -O /etc/apt/keyrings/grafana.asc https://apt.grafana.com/gpg-full.key
sudo chmod 644 /etc/apt/keyrings/grafana.asc

echo "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

sudo apt update
if [ ! -f "/etc/apt/sources.list.d/grafana.sources" ]; then
    sudo apt modernize-sources -y
fi
sudo apt install grafana

sudo cp grafana-server.service /usr/lib/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable grafana-server.service

./configure_grafana
source /usr/local/bin/gcx_token.env

sudo /usr/sbin/grafana cli plugins install volkovlabs-form-panel

# install and configure gcx (cli control)
sudo apt install -y curl
curl -fsSL https://raw.githubusercontent.com/grafana/gcx/main/scripts/install.sh | sh

if ! grep -q '.local/bin' "$HOME/.bashrc"; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
fi
. ~/.bashrc

gcx config set contexts.default.grafana.server http://localhost:3000
gcx config set contexts.default.grafana.org-id 1
gcx config set contexts.default.grafana.auth-method token
gcx config set contexts.default.grafana.token $GRAFANA_API_TOKEN

push_dashboards ~/dashboards_json/dashboards.v2.dashboard.grafana.app

# configure mysql datasource
sudo cp impish.yaml /etc/grafana/provisioning/datasources
sudo systemctl restart grafana-server.service
