#!/bin/bash

scripts="configure_bashrc install_scripts configure_system_python_env install_services configure_vpn install_mysql install_grafana"
for s in $scripts; do
    echo "executing $s"
    ./"$s"
    echo "done $s"
done
