#!/python-venv/bin/python

import os
import socket
import sys
import time

from impisc.daqbox import daqbox_api as dbapi
from impisc import logging

mode = sys.argv[1]
options = ("spectrum", "waveform")
if mode not in options:
    raise ValueError(f"Mode {mode} not supported; choose from {options}")

num_packets = int(sys.argv[2])

channel = None
if len(sys.argv) > 3:
    channel = int(sys.argv[3])
    if channel not in range(0, 4):
        raise ValueError("Channel selection needs to be in [0, 4)")

# Update the DAQBOX configuration
ACTIVE_CONFIG = "/data/config/daqbox_config.json"
cfg = dbapi.DaqBoxConfig.from_file(ACTIVE_CONFIG)
cfg.acquisition_mode = mode

iface = dbapi.DaqBoxInterface()
iface.send(dbapi.STOP, expect_handshake=False)
iface.send(cfg.to_packet(), expect_handshake=False)

iface.send(dbapi.START, expect_handshake=False)
# Clear some of the data, because they could be bad
iface.flush(max_iterations=32)

# Block so that we don't time out before packets start coming in
iface.sock.setblocking(True)

# Acquire and forward data
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
dest = ("localhost", int(os.getenv(f"DEBUG_{mode.upper()}_PORT")))

i = 0
channel_select = (mode == "waveform") and (channel is not None)
while i < num_packets:
    try:
        data = iface.recv()
        if channel_select:
            if data[2] != channel:
                continue
        sock.sendto(data, dest)
        i += 1
    except BlockingIOError:
        logging.log_warning("no debug packets available yet")
        time.sleep(0.1)

iface.sock.setblocking(False)
iface.send(dbapi.STOP, expect_handshake=False)
iface.sock.close()
