#!/bin/bash
# Prints the status bits for the other services
# Left pads zeros to make one full byte

# Explicitly define this so we know the exact order
# (as opposed to using `ls` or `find`)
declare -a services=(
    "command-executor.service"
    "command-router.service"
    "nominal-science.service"
    "quicklook.service"
    "science-rebinner.service"
    "science-redirector.service"
)
echo -n 00
for service in "${services[@]}"; do
    service-status $service
done
