#!/bin/bash

source /data/config/variables.env


# Turn on the bias and daqbox and one preamp channel for initial
# recalibration
turn_me_on="1 2 3 4 daqbox bias"
for t in $turn_me_on; do
    toggle_power $t on
done

# Wait for power to stabilize
sleep 5
set_bias $SCIENCE_BIAS_VOLTAGE

setup_daqbox_network enp1s0
# Wait for network to come up
sleep 10

# Recalibrate the baseline before science begins
recalibrate_daqbox

if [ $? -ne 0 ]; then
    stop_science
    echo "<2> Failed to recalibrate DAQBOX after several attempts" >&2
    exit 1
fi

sudo systemctl start nominal-science.service
