#!/bin/bash

source /data/config/variables.env
udpcapture --port $LOCAL_HEALTH_FWD_PORT --base-filename '/data/health/impish_health' \
	--file-lifetime 300 --forward-addrs "127.0.0.1:$TELEMETER_PORT"\
	--post-process-cmd 'xz $out_file'
