#!/bin/bash
# Prints the status bits for the `udpcapture` services
# Left pads zeros to make one full byte

# Explicitly define this so we know the exact order
# (as opposed to using `ls` or `find`)
declare -a services=(
    "debug-spectrum-udpcapture.service"
    "debug-waveform-udpcapture.service"
    "health-udpcapture.service"
    "quicklook-udpcapture.service"
    "rtd-udpcapture.service"
    "science-udpcapture.service"
)
echo -n 00
for service in "${services[@]}"; do
  service_status $service
done
