#!/python-venv/bin/python3

import argparse
import os
import socket

from collections.abc import Iterator
from pathlib import Path

from impisc import logging, packets

# Currently, all scripts in /usr/local/bin should be safe...
globbed: Iterator[Path] = Path("/usr/local/bin").glob("*")
SAFE_COMMANDS: list[str] = [str(p.name) for p in globbed if p.is_file() and os.access(p, os.X_OK)] + [
    # other commands we want to define as safe
]
# Special commands that are executed within this process
# rather than getting passed of the command-executor.
SPECIAL_COMMANDS: list[str] = [
    "restart-executor",
    "reboot",
    "poweroff"
]
logging.log_info(f"Safe commands: {SAFE_COMMANDS}")
logging.log_info(f"Special commands: {SPECIAL_COMMANDS}")
UNLOCK_TIMEOUT = 10  # seconds


def main():
    args = parse_args()
    logging.log_info(f"Binding to port {args.listen_port}")
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("", args.listen_port))
    # The maximum transmission unit defined by the Gondola network
    MTU = 9100
    while True:
        # Assume the commands are whitespace-delimited ascii
        command: str = sock.recv(MTU).decode("utf-8")
        error: str | None = None
        match command:
            case x if x in SPECIAL_COMMANDS:
                logging.log_critical(f"Received special command {command}; executing")
                exit_code = os.system(f"sudo {command}")
                logging.log_info(f"Special command exitted with code {exit_code}")
            case x if x in SAFE_COMMANDS:
                logging.log_info(f"Received safe command {command}")
                error = execute_command(command, args.executor_port)
            case "unlock":
                sock.settimeout(UNLOCK_TIMEOUT)
                try:
                    command = sock.recv(MTU)#.decode("utf-8")
                    logging.log_info(f"Received UNSAFE command {command}")
                    error = execute_command(command, args.executor_port)
                except socket.timeout:
                    logging.log_warning(f"Socket timed out while waiting for unsafe command, relocking")
                finally:
                    sock.settimeout(None)
            case _:
                logging.log_warning(f"Received command \"{command}\" either unknown or unsafe without unlocking; doing nothing")
        if error:
            send_error(sock, args.endpoint_port, error)


def execute_command(cmd: str, port: int):
    """The executor is an external program,
    so let it deal with any issues.
    If it gets stuck... we will need to issue the "reset" special
    command.
    """
    logging.log_critical(f"Executing command \"{cmd}\" on port {port}")
    len_sent: int = socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(
        bytes(cmd, encoding="utf-8"), ("localhost", port)
    )
    logging.log_info(f"Sent {len_sent} out of {len(cmd)} bytes")


def execute_canned_command(cmd: str, endpoint: int) -> str | None:
    """
    A canned command corresponds to a script we have already written,
        or one of the special commands enumerated in the function body.

    The canned command may accept arguments, or not.
    Aside from the special commands,
        a canned command must exist in /usr/local/bin,
        which is the common install point for scripts.
    """
    command_name, _ = cmd.split(maxsplit=1)

    # A few special commands...
    special_commands = ["restart-executor", "reboot", "poweroff"]
    if command_name in special_commands:
        os.system(f"sudo {command_name}")
        return f"Executed special command {command_name}; check journal for issues"

    listing = os.listdir("/usr/local/bin")
    if command_name not in listing:
        return f"{command_name} is not a canned command"

    return execute_arbitrary_command(cmd, endpoint)


def execute_arbitrary_command(cmd: str, endpoint: int) -> None:
    """
    The arbitrary executor is an external program,
    so let it deal with any issues.
    If it gets stuck...we will need to issue the "reset" special
    command.
    """
    socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(
        bytes(cmd), ("localhost", endpoint)
    )


def send_error(s: socket.socket, dest: int, msg: str) -> None:
    packet = packets.CommandResponsePacket()
    packet.add_response(msg)
    len_sent = s.sendto(packet, ("127.0.0.1", dest))
    logging.log_info(f"Sending error message (len: {len_sent}) to port {dest}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Route commands appropriately for IMPISH"
    )
    _= parser.add_argument(
        "-p",
        "--listen_port",
        help="UDP port to listen on (bind to)",
        type=int,
        required=True,
    )
    _= parser.add_argument(
        "-e",
        "--endpoint_port",
        help="Local UDP port to forward any data, like a command reply or error message.",
        type=int,
    )
    _= parser.add_argument(
        "-x",
        "--executor_port",
        help="Which port to send arbitrary command execution requests",
        type=int,
    )
    return parser.parse_args()


if __name__ == "__main__":
    main()
