#!/python-venv/bin/python3

from impisc import packets
import os
import socket
import argparse


def main():
    args = parse_args()
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("", args.listen_port))

    # The maximum transmission unit defined by the Gondola network
    MTU = 9100
    while True:
        # Assume the commands are whitespace-delimited ascii
        command = sock.recv(MTU).decode("utf-8")
        cmd_type, command = command.split(maxsplit=1)

        error = None
        match cmd_type:
            case "canned":
                error = execute_canned_command(command, args.arbitrary_endpoint)
            case "arbitrary":
                error = execute_arbitrary_command(command, args.arbitrary_endpoint)
            case _:
                error = f"unknown command type {cmd_type}"

        if error:
            send_error(sock, args.endpoint_port, error)


def execute_canned_command(cmd: str, endpoint: int) -> str | None:
    """
    A canned command corresponds to a script we have already written,
        or one of the special commands enumerated in the function body.

    The canned command may accept arguments, or not.
    Aside from the special commands,
        a canned command must exist in /usr/local/bin,
        which is the common install point for scripts.
    """
    command_name, _ = cmd.split(maxsplit=1)

    # A few special commands...
    special_commands = ["restart-executor", "reboot", "poweroff"]
    if command_name in special_commands:
        os.system(f"sudo {command_name}")
        return f"Executed special command {command_name}; check journal for issues"

    listing = os.listdir("/usr/local/bin")
    if command_name not in listing:
        return f"{command_name} is not a canned command"

    return execute_arbitrary_command(cmd, endpoint)


def execute_arbitrary_command(cmd: str, endpoint: int) -> None:
    """
    The arbitrary executor is an external program,
    so let it deal with any issues.
    If it gets stuck...we will need to issue the "reset" special
    command.
    """
    socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(
        bytes(cmd), ("localhost", endpoint)
    )


def send_error(s: socket.socket, dest: int, msg: str) -> None:
    packet = packets.CommandResponse()
    packet.add_response(msg)
    s.sendto(packet, ("127.0.0.1", dest))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Route commands appropriately for IMPISH"
    )
    parser.add_argument(
        "-p",
        "--listen_port",
        help="UDP port to listen on (bind to)",
        type=int,
        required=True,
    )
    parser.add_argument(
        "-e",
        "--endpoint_port",
        help="Local UDP port to forward any data, like a command reply or error message.",
        type=int,
    )
    parser.add_argument(
        "-x",
        "--executor_port",
        help="Which port to send arbitrary command execution requests",
        type=int,
    )
    return parser.parse_args()


if __name__ == "__main__":
    main()
