#!/python-venv/bin/python
"""
Applies the header to every packet passing through this process.
The stamped packets then get sent to the starspec-forwarder process
and subsequently sent to the gondola.
"""

import os
import socket

from impisc import logging, packets
from impisc.packets import PacketHeader


TELE_PORT = int(os.environ["HEADER_STAMPER_PORT"])
SS_FWD_PORT = int(os.environ["ENDPOINT_PORT"])
SEQUENCE_IDS = {
    "total": 0,
    packets.HealthPacket: 0,
    packets.QuicklookPacket: 0,
    packets.CommandResponsePacket: 0,
}
PACKET_PORTS = {
    int(os.environ["LOCAL_HEALTH_FWD_PORT"]): packets.HealthPacket,
    int(
        os.environ["QUICKLOOK_UDPCAP_PORT"]
    ): packets.QuicklookPacket,  # TODO: confirm this port number for quicklook
    int(os.environ["COMMAND_ROUTER_PORT"]): packets.CommandResponsePacket,
    int(os.environ["COMMAND_EXECUTOR_PORT"]): packets.CommandResponsePacket,
}


def make_header(recv_port: int, packet_size: int) -> packets.PacketHeader:
    """Create the header based on the number of bytes in the packet.
    And increment the packet sequence number.
    """
    PacketClass = PACKET_PORTS[recv_port]
    header: PacketHeader = packets.PacketHeader()
    header.id = packets.PACKET_IDS.index(PacketClass)
    header.packet_number = SEQUENCE_IDS["total"]
    header.sequence_number = SEQUENCE_IDS[PacketClass]
    header.packet_size = packet_size
    logging.log_info(
        f"Packet type {PacketClass}\nID: {header.id}  NUM: {header.packet_number}  "
        + f"SEQ: {header.sequence_number:>6}  SIZE: {header.packet_size:>5}"
    )
    SEQUENCE_IDS["total"] = (SEQUENCE_IDS["total"] + 1) % (
        packets.MAX_SEQUENCE_NUMBER + 1
    )
    SEQUENCE_IDS[PacketClass] = (SEQUENCE_IDS[PacketClass] + 1) % (
        packets.MAX_SEQUENCE_NUMBER + 1
    )

    return header


def main():
    """Endlessly loop and listen for incoming packets.
    Stamps the header onto each packet and increments a sequence
    ID for each type of packet.
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    logging.log_debug(f"Binding to port {TELE_PORT}")
    sock.bind(("", TELE_PORT))
    while True:
        data, addr = sock.recvfrom(8192)  # pyright: ignore[reportAny]
        logging.log_debug(f"Received {len(data)} bytes from {addr[0]}:{addr[1]}")
        recv_port: int = addr[1]
        if recv_port in PACKET_PORTS and len(data) != 0:
            header = make_header(recv_port, len(data))
            full_packet: bytes = bytes(header) + data
            num_sent = sock.sendto(full_packet, ("", SS_FWD_PORT))
            logging.log_debug(
                f"Sent {num_sent} out of {len(full_packet)} bytes to StarSpec forwarder (port {SS_FWD_PORT})"
            )
            if num_sent != len(full_packet):
                logging.log_warning("Byte loss when sending previous packet")
        else:
            logging.log_warning(
                f"Unknown packet ({len(data)} bytes) received "
                + f"on port {TELE_PORT} from {addr[0]}:{addr[1]}; discarding;\n{data}"
            )


if __name__ == "__main__":
    main()
