#!/python-venv/bin/python
"""
Applies the header to every packet passing through this process.
The stamped packets then get sent to the starspec-forwarder process
and subsequently sent to the gondola.
"""

import ctypes
import os
import socket

from impisc import logging, packets
from impisc.packets import PacketHeader


TELE_PORT = int(os.getenv("HEADER_STAMPER_PORT"))
SS_FWD_PORT = int(os.getenv("ENDPOINT_PORT"))
SEQUENCE_IDS = {
    packets.HealthPacket: 0,
    packets.QuicklookPacket: 0,
    packets.CommandResponsePacket: 0
}
PACKET_SIZES = {
    ctypes.sizeof(p) : p for p in SEQUENCE_IDS.keys()
}


def make_header(num_bytes: int) -> packets.PacketHeader:
    """Create the header based on the number of bytes in the packet.
    And increment the packet sequence number.
    """
    PacketClass = PACKET_SIZES[num_bytes]
    header: PacketHeader = packets.PacketHeader()
    header.id = packets.PACKET_IDS.index(PacketClass)
    header.sequence_number = SEQUENCE_IDS[PacketClass]
    header.packet_size = num_bytes
    logging.log_info(f"Packet type {PacketClass}\nID: {header.id}  SEQ: {header.sequence_number:>6}  SIZE: {header.packet_size:>5}")
    SEQUENCE_IDS[PacketClass] = (SEQUENCE_IDS[PacketClass] + 1) % (packets.MAX_SEQUENCE_NUMBER + 1)

    return header


def main():
    """Endlessly loop and listen for incoming packets.
    Stamps the header onto each packet and increments a sequence
    ID for each type of packet.
    """
    sock =socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    logging.log_debug(f"Binding to port {TELE_PORT}")
    sock.bind(("", TELE_PORT))
    while True:
        data, addr = sock.recvfrom(8192)  # pyright: ignore[reportAny]
        if len(data) in PACKET_SIZES:
            logging.log_debug(f"Received {len(data)} bytes from {addr[0]}:{addr[1]}")
            header: PacketHeader = make_header(num_bytes=len(data))
            payload: bytes = bytes(header) + data
            num_sent = sock.sendto(payload, ("", SS_FWD_PORT))
            logging.log_info(f"Sent {num_sent} out of {len(payload)} bytes to StarSpec forwarder (port {SS_FWD_PORT})")
            if num_sent != len(data):
                logging.log_warning(f"Byte loss when sending previous packet")
        else:
            logging.log_warning(
                f"Unknown packet ({len(data)} bytes) received "
                + f"on port {TELE_PORT} from {addr[0]}:{addr[1]}; discarding;\n{data}"
            )


if __name__ == "__main__":
    main()
