#!/python-venv/bin/python
"""
Basic heater control based on a low temperature threshold and hysteresis.
All temperatures in units of degrees Celsius.
"""


import ctypes
import os
import socket

from typing import Literal

from impisc import logging
from impisc.packets import RTDPacket


INSTRUMENT_HEATER_RTD_CHANNEL: int = 7
ELECTRONICS_HEATER_RTD_CHANNEL: int = 7
HEATER_TRIGGER_TEMPERATURE: int = int(os.getenv("HEATER_TRIGGER_TEMPERATURE"))
HEATER_HYSTERESIS: int = int(os.getenv("HEATER_HYSTERESIS"))
MY_PORT: int = int(os.getenv("HEATER_CONTROLLER_PORT"))


def set_heater_state(state: Literal["on", "off"]):
    """Set the heater state with the toggle_power command."""
    if state not in ["on", "off"]:
        raise ValueError(f"Specified heater state invalid: {state}\nDoing nothing.")
    cmd: str = f"toggle_power heater {state}"
    logging.log_info(f"Issuing command: {cmd}")
    os.system(cmd)


def main():
    
    set_heater_state("off")
    heater_on: bool = False
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("localhost", MY_PORT))
    while True:
        data: bytes = sock.recv(ctypes.sizeof(RTDPacket))
        packet: RTDPacket = RTDPacket.from_buffer_copy(data)
        instrument_temperature = getattr(packet, f"temperature{INSTRUMENT_HEATER_RTD_CHANNEL}")
        electronics_temperature = getattr(packet, f"temperature{ELECTRONICS_HEATER_RTD_CHANNEL}")
        temps_to_compare = []
        for temp in [instrument_temperature, electronics_temperature]:
            if temp != -127:
                temps_to_compare.append(temp)
        match heater_on:
            case True:
                if max(temps_to_compare) > HEATER_TRIGGER_TEMPERATURE + HEATER_HYSTERESIS:
                    set_heater_state("off")
                    heater_on = False
            case False:
                if min(temps_to_compare) < HEATER_TRIGGER_TEMPERATURE:
                    set_heater_state("on")
                    heater_on = True


if __name__ == "__main__":
    main()
