#!/python-venv/bin/python
"""
Basic heater control based on a low temperature threshold and hysteresis.
All temperatures in units of degrees Celsius.
"""


import ctypes
import os
import socket

from typing import Literal

from impisc import logging
from impisc.packets import TemperaturePacket


INSTRUMENT_HEATER_RTD_CHANNEL: int = 4
ELECTRONICS_HEATER_RTD_CHANNEL: int = 4
HEATER_TRIGGER_TEMPERATURE: int = int(os.getenv("HEATER_TRIGGER_TEMPERATURE"))
HEATER_HYSTERESIS: int = int(os.getenv("HEATER_HYSTERESIS"))
MY_PORT: int = int(os.getenv("HEATER_CONTROLLER_PORT"))


def set_heater_state(state: Literal["on", "off"]):
    """Set the heater state with the `toggle_power` command.
    Executes using os.system
    """
    if state not in ["on", "off"]:
        raise ValueError(f"Specified heater state invalid: {state}\nDoing nothing.")
    cmd: str = f"toggle_power heater {state}"
    logging.log_info(f"Toggling heaters {state}")
    os.system(cmd)


def main():
    """Infinitely loop, receiving temperature packets and comparing the RTDs
    attached to the heaters against the trigger temperature.
    """
    set_heater_state("off")
    heater_on: bool = False
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("localhost", MY_PORT))
    logging.log_debug(f"Binding to port {MY_PORT}")
    logging.log_debug(f"Instrument channel: {INSTRUMENT_HEATER_RTD_CHANNEL}\nElectronics channel: {ELECTRONICS_HEATER_RTD_CHANNEL}")
    logging.log_debug(f"Heater trigger temperature {HEATER_TRIGGER_TEMPERATURE} C with hysteresis {HEATER_HYSTERESIS} C")
    while True:
        data: bytes = sock.recv(ctypes.sizeof(TemperaturePacket))
        packet: TemperaturePacket = TemperaturePacket.from_buffer_copy(data)
        instrument_temperature: float = getattr(packet, f"temperature{INSTRUMENT_HEATER_RTD_CHANNEL}")
        electronics_temperature: float = getattr(packet, f"temperature{ELECTRONICS_HEATER_RTD_CHANNEL}")
        temps_to_compare: list[float] = []
        for temp in [instrument_temperature, electronics_temperature]:
            if temp != TemperaturePacket.NULL_RTD_VALUE:
                temps_to_compare.append(temp)
        if heater_on:
            if (max(temps_to_compare) / 10) > HEATER_TRIGGER_TEMPERATURE + HEATER_HYSTERESIS:
                set_heater_state("off")
                heater_on = False
        else:
            if (min(temps_to_compare) / 10) < HEATER_TRIGGER_TEMPERATURE:
                set_heater_state("on")
                heater_on = True


if __name__ == "__main__":
    main()
