#!/python-venv/bin/python

"""
Accept DAQBOX spectrum packets on a port and sum them into an N-element
    histogram of unsigned 32-bit entries (quicklook histogram).
Send the histogram to a destination ip:port.
The number of seconds to integrate,
    the edges used to rebin the data,
    the destination IP address,
    and the listen port are set via environment variables.
"""

import argparse
import socket
from impisc import logging
from impisc.et_daqbox import daq_box_api as dba
from impisc import packets


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-l",
        "--listen_port",
        required=True,
        help="Port to receive science packetes on",
        type=int,
    )
    parser.add_argument(
        "-d",
        "--destination_port",
        required=True,
        help="Port to send science packets to",
        type=int,
    )
    parser.add_argument(
        "-e",
        "--rebin_edges",
        required=True,
        help="Dash-delimited list of edges to rebin science packets",
        type=str,
    )
    parser.add_argument(
        "-s",
        "--summation_time",
        required=True,
        help="Number of seconds to sum over per quicklook packet",
        type=int,
    )
    return parser.parse_args()


def main():
    # Format: "edge1-edge2-edge3-edge4-edge5-...",
    # number of edges depends on number of quicklook bins
    args = parse_args()
    rebin_edges = [int(x) for x in args.rebin_edges.split("-")]
    if len(rebin_edges) != (packets.NUM_QLOOK_BINS + 1):
        raise ValueError(
            f"Incorrect number of rebin edges: {len(rebin_edges)} instead of "
            f"{packets.NUM_QLOOK_BINS + 1}"
        )

    seconds_integration = args.summation_time
    # Frame rate = 32 spectra/sec
    spectra_per_packet = 32 * seconds_integration

    destination = (
        "127.0.0.1",
        args.destination_port,
    )
    receive_port = args.listen_port

    my_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    my_socket.bind(("", receive_port))

    qpack = packets.QuicklookPacket()
    accumulated = 0
    while True:
        data = my_socket.recv(8200)
        if len(data) != 8005:
            # Bad packet for some reason...
            continue
        # Skip the timestamp and frame counter (4 + 1 = 5B to skip)
        parsed = dba.parse_spectrum_packet(data[5:])
        for chan in range(4):
            for edge_idx in range(len(rebin_edges) - 1):
                # Iterate over the rebin edges, and use the same index
                # to index the bin in the output array
                a, b = rebin_edges[edge_idx], rebin_edges[edge_idx + 1]
                qpack.channels[chan].counts[edge_idx] += sum(parsed[chan][a:b])

        accumulated = (accumulated + 1) % spectra_per_packet
        if accumulated == 0:
            my_socket.sendto(qpack, destination)
            qpack = packets.QuicklookPacket()


if __name__ == "__main__":
    main()
