#!/python-venv/bin/python3
import argparse
import ctypes
import time
import socket
import sys
import subprocess
from impisc.daqbox import daqbox_api as dba


# DAQBOX framerate
FRAMERATE = 32
daqbox = None


def handle_sigint():
    """The SIGINT (Ctrl + C) signal is used at an interactive terminal as well as
    the `timeout` command. Handle it here by telling the DAQBOX to stop data acquisition
    and close its socket gracefully."""
    if daqbox is None:
        sys.exit(0)

    daqbox.send(dba.STOP, expect_handshake=False)
    daqbox.sock.close()
    sys.exit(0)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Configure DAQBOX for science data acquisition and begin forwarding packets to "
            "a UDP endpoint, specified by the destination_port. A configuration file name must be passed "
            "as an argument."
        )
    )
    parser.add_argument(
        "-p",
        "--destination_port",
        required=True,
        help="Destination UDP port to forward timestamps and spectrum packets",
        type=int,
    )
    parser.add_argument(
        "-c",
        "--config_file",
        required=True,
        help="Configuration file path for DAQBOX config",
        type=str,
    )
    return parser.parse_args()


def await_pps():
    PPS_PIN = 16
    res = subprocess.run(["detect-edge", f"{PPS_PIN}"])
    if res.returncode != 0:
        raise ValueError("Cannot detect PPS on requested pin")


def init_daqbox(config_file: str) -> dba.DaqBoxInterface:
    config = dba.DaqBoxConfig.from_file(config_file)
    # Always use spectrum mode for science data
    config.acquisition_mode = "spectrum"
    iface = dba.DaqBoxInterface()
    iface.send(config.to_packet(), expect_handshake=True)
    return iface


def main():
    args = parse_args()

    # Specify that we're modifying the global
    # state so the variable can be accessed elsewhere
    global daqbox
    daqbox = init_daqbox(args.config_file)

    # Start up a UDP socket for forwarding data
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    await_pps()
    # Save the timestamp immediately after the PPS tick:
    # we will increment it in the loop based on the number of packets
    # received.
    timestamp = int(time.time())

    daqbox.send(dba.START, expect_handshake=True)
    # Set the daqbox receive socket to block for data
    daqbox.sock.setblocking(True)
    destination: tuple[str, int] = ("localhost", int(args.destination_port))

    # Loop forever, forwarding spectrum packets and timestamps
    packet_counter = 0
    while True:
        if packet_counter == 0:
            # A full second has passed, or we are
            # awaiting data acquisition start
            timestamp += 1
        packet = (
            bytes(ctypes.c_uint32(timestamp))
            + bytes(ctypes.c_uint8(packet_counter))
            + daqbox.recv()
        )
        sock.sendto(packet, destination)
        packet_counter = (packet_counter + 1) % FRAMERATE


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        handle_sigint()
