#!/python-venv/bin/python3
import argparse
import ctypes
import time
import socket
import subprocess
from impisc.daqbox import daqbox_api as dba


# DAQBOX framerate
FRAMERATE = 32


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Configure DAQBOX for science data acquisition and begin forwarding packets to "
            "a UDP endpoint, specified by the destination_port. A configuration file name must be passed "
            "as an argument."
        )
    )
    parser.add_argument(
        "-p",
        "--spectrum_port",
        required=True,
        help="Destination UDP port to forward timestamps and spectrum packets",
        type=int,
    )
    parser.add_argument(
        "-c",
        "--config_file",
        required=True,
        help="Configuration file path for DAQBOX config",
        type=str,
    )
    parser.add_argument(
        "-t",
        "--time_between_wforms",
        required=False,
        help="Time (seconds) between taking periodic waveform acquisitions",
        type=int,
    )
    parser.add_argument(
        "-n",
        "--num_wforms",
        required=False,
        help="The number of waveforms to acquire during each periodic acquisition",
        type=int,
        default=1,
    )
    parser.add_argument(
        "-w",
        "--waveform_port",
        required=False,
        help="Port to forward waveform packets",
        type=int,
    )
    return parser.parse_args()


def await_pps() -> int:
    PPS_PIN = 16
    res = subprocess.run(["detect-edge", f"{PPS_PIN}"])
    if res.returncode != 0:
        raise ValueError("Cannot detect PPS on requested pin")
    return int(time.time())


def init_daqbox(config_file: str, mode: str = "spectrum") -> dba.DaqBoxInterface:
    config = dba.DaqBoxConfig.from_file(config_file)
    config.acquisition_mode = mode
    iface = dba.DaqBoxInterface()
    iface.send(config.to_packet(), expect_handshake=True)
    iface.flush(max_iterations=128)
    return iface


def main():
    args = parse_args()
    if (args.waveform_port is None and args.time_between_wforms is not None) or (
        args.time_between_wforms is None and args.waveform_port is not None
    ):
        raise ValueError(
            "If the waveform port is provided, the time between waveforms must also "
            "be provided, and vise-versa."
        )

    spectrum_destination: tuple[str, int] = ("localhost", args.spectrum_port)
    # Port could be None, so annotate that.
    waveform_destination: tuple[str, int | None] = ("localhost", args.waveform_port)
    daqbox = init_daqbox(args.config_file)

    frames_between_wforms = (
        args.time_between_wforms * FRAMERATE
        if args.time_between_wforms is not None
        else None
    )

    # Start up a UDP socket for forwarding data
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    # Save the timestamp immediately after the PPS tick:
    # we will increment it in the loop based on the number of packets
    # received.
    timestamp = await_pps()
    daqbox.send(dba.START, expect_handshake=True)

    # Loop forever, forwarding spectrum packets and timestamps
    timestamp_counter = 0
    waveform_counter = 0
    while True:
        time_for_a_waveform: bool = (
            frames_between_wforms is not None and waveform_counter == 0
        )
        if time_for_a_waveform:
            _ = daqbox.send(dba.STOP, expect_handshake=False)
            daqbox.sock.close()
            del daqbox
            daqbox = init_daqbox(args.config_file, mode="waveform")

            # Take a single waveform and save it
            _ = daqbox.send(dba.START, expect_handshake=True)
            for i in range(args.num_wforms):
                wform = daqbox.recv()
                sock.sendto(wform, waveform_destination)

            # Return to spectrum mode
            _ = daqbox.send(dba.STOP, expect_handshake=False)
            daqbox.sock.close()
            del daqbox
            daqbox = init_daqbox(args.config_file, mode="spectrum")

            # Restart collection and re-align to new PPS tick
            timestamp = await_pps()
            timestamp_counter = 0
            _ = daqbox.send(dba.START, expect_handshake=True)
            # Set the daqbox receive socket to block for data
            daqbox.sock.setblocking(True)
            daqbox.flush(max_iterations=128)

        if timestamp_counter == 0:
            # A full second has passed, or we are
            # awaiting data acquisition start
            timestamp += 1

        packet = (
            bytes(ctypes.c_uint32(timestamp))
            + bytes(ctypes.c_uint8(timestamp_counter))
            + daqbox.recv()
        )
        sock.sendto(packet, spectrum_destination)
        timestamp_counter = (timestamp_counter + 1) % FRAMERATE
        if frames_between_wforms is not None:
            waveform_counter = (waveform_counter + 1) % frames_between_wforms


if __name__ == "__main__":
    main()
