#!/python-venv/bin/python
import subprocess
import socket
import os


def packet_to_hex(data: bytes) -> str:
    """Format a data packet as zero-padded hexadecimal,
       encoded as a string"""
    return ''.join(format(d, "02x") for d in data)


def main():
    port = int(os.getenv("ENDPOINT_PORT"))
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("", port))
    while True:
        data = sock.recv(8192)
        if len(data) == 0:
            continue
        subprocess.run(
            # StarSpec uses the `serde` Rust package for their
            # database connectivity, so we need to call an external
            # program to use it.
            [f"oneshot-forwarder {packet_to_hex(data)}"],
            shell=True,
        )

if __name__ == "__main__":
    main()
