#!/bin/bash
# Install systemd services and associated process programs

# Install all processes
processes=$(ls ../processes)
for s in $processes; do
    sudo cp "../processes/$s" "/usr/local/bin"
done

# Install all .service files and enable them
services=$(ls ../services/*.service)
for s in $services; do
    echo $s
    sudo cp "../services/$s" "/etc/systemd/system"
done
sudo cp "../services/relay-variables.env" "/usr/local/bin"
sudo cp "../../services/variables.env" "/usr/local/bin"

sudo systemctl daemon-reload
for s in $services; do
    sudo systemctl restart "$(basename $s)"
done
