#!/bin/bash

# Delete Pi packages/services we don't need,
# like video/audio and Bluetooth

# Avahi: network device config. Useless
sudo systemctl stop avahi-daemon
sudo systemctl disable avahi-daemon
sudo apt purge -y avahi-daemon

# Bluetooth: we really don't need it
sudo systemctl stop bluetooth
sudo systemctl disable bluetooth
sudo apt purge -y bluez bluez-tools blueman

# Misc stuff from apt
sudo apt purge -y firmware-atheros firmware-brcm80211 firmware-libertas firmware-mediatek firmware-realtek

# Delete old/unused deps
sudo apt autoremove -y
sudo apt autoclean -y
